name: Build and Deploy Prisma Introspection

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: write

jobs:
  execute-code-quality-validation:
    uses: ./.github/workflows/validate.yml
    with:
      eslint-enable: true
      unit-test-enable: false
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  execute-release:
    needs: execute-code-quality-validation
    uses: ./.github/workflows/release.yml
    with:
      branches: "${{ github.ref_name }}"
      slack_enabled: true
      npm_publish_enabled: false
    secrets:
      token: ${{ secrets.GH_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      npm_token: ${{ secrets.NPM_TOKEN }}
  deploy:
     needs: execute-release
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 

       - name: Set Branch Name
         id: branch_name
         run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

       - name: Set Latest Tag
         id: set_latest_tag
         run: |
           LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")
           echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
           echo "Latest tag is ${{ env.LATEST_TAG }}"

